name: Test Master
on: push

jobs:
  TEST_BACKEND:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ğŸªœ Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: ğŸ’¾ Cache
        if: github.ref != 'refs/heads/master'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-            

      - name: ğŸ›’ Setup postgres database
        uses: m4nu56/postgresql-action@1.0
        with:
          postgresql version: latest
          postgresql user: postgres
          postgresql password: postgres

      - name: chmod +x ./gradlew
        run: chmod +x ./gradlew

      - name: ğŸ•‹  TEST
        run: ./gradlew test -Dspring.profiles.active=postgres

      - name: ğŸ“¹ Jacoco test report
        run: ./gradlew jacocoTestReport
      - name: ğŸ Test codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
